name: kwant-latest
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - kwant
    # required dependencies
    - numpy
    - scipy
    # Temporary due to https://github.com/conda-forge/mumps-feedstock/issues/106
    - metis !=5.1.1
    # optional dependencies
    - matplotlib-base
    - sympy
    - plotly
    - pip:
        - qsymm
